### ISSUE TITLE
Create user's guide

### ISSUE THREAD

**Issue by aprokop** [trilinos/ForTrilinos#209] opened 2018-01-30 16:58 UTC
- [ ] Migrate pieces of [design document](https://trilinos.github.io/ForTrilinos/files/ForTrilinos_Design_Document.pdf) to sphinx on RTD
- [ ] Expand Build Section
- [ ] Figure out a way to (semi-)automatically export sphinx to tex for the standalone user's guide

**Comment by sethrj** [comment] 2019-02-05 23:53
Duplicate of #159?

**Closed** 2019-02-06 14:37 UTC
Labels: type: documentation
