### ISSUE TITLE
Configure failures after recent ForTrilinos update

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/ForTrilinos#195] opened 2017-12-19 19:29 UTC
@trilinos/framework 
@bartlettroscoe 
@aprokop 

After the recent ForTrilinos update, the Trilinos dashboard is experiencing a large number of failures like this:

[https://testing.sandia.gov/cdash/viewConfigure.php?buildid=3282438](https://testing.sandia.gov/cdash/viewConfigure.php?buildid=3282438)

**Comment by aprokop** [comment] 2017-12-19 19:51
@jwillenbring OK. I'm not surprised. I'm surprised that the `master` branch of ForTrilinos is being nightly tested in Trilinos. I did not think that to be the case. Could you explain exactly how and what is being tested?

**Comment by bartlettroscoe** [comment] 2017-12-19 20:02
The ForTrilinos repo is cloned as part of nightly Trilinos testing but is labeled as EX.  But even EX packages will have their Dependencies.cmake files processed because they could be enabled.

I will comment in more detail in trilinos/Trilinos#2085 on how to address this short-term in the context of Trilinos testing.

**Comment by aprokop** [comment] 2017-12-19 20:06
@bartlettroscoe OK. So, if I understand correctly, I just need to resolve the `Dependencies.cmake`, even though the code cannot be compiled, right?

**Comment by bartlettroscoe** [comment] 2017-12-19 20:10
@aprokop,

> OK. So, if I understand correctly, I just need to resolve the Dependencies.cmake, even though the code cannot be compiled, right?

Yes, the Dependencies.cmake files have to be correct if TriBITS does not enable the package.  If you don't want to even have the Dependencies.cmake files processed, then you need to completely hide that package from Trilinos.  I am doing that right now for Trilinos short term.  We can discuss better intermediate-term solutions for this issue after that.

**Comment by aprokop** [comment] 2017-12-19 20:12
@bartlettroscoe Thanks for the explanation. This must be a recent change in TriBITs as I was using 12.12.1 version. I'll push a fix. I assume that the empty `Dependencies.cmake` with the following content is going to be sufficient?
```CMake
TRIBITS_PACKAGE_DEFINE_DEPENDENCIES(       )                                                                                                                   
```

**Comment by bartlettroscoe** [comment] 2017-12-19 20:19
> I assume that the empty Dependencies.cmake with the following content is going to be sufficient?

Yes.  But I don't think that any version of TriBITS would allow for missing subpackage Dependencies.cmake files (unless you specifically ask it to).

**Comment by aprokop** [comment] 2017-12-19 20:20
> But I don't think that any version of TriBITS would allow for missing subpackage Dependencies.cmake files (unless you specifically ask it to).

That's not my experience. I'm not touching TriBITS at all, but it still allows configuring and building current ForTrilinos without this change.

**Comment by bartlettroscoe** [comment] 2017-12-19 20:27
@aprokop,

> That's not my experience. I'm not touching TriBITS at all, but it still allows configuring and building current ForTrilinos without this change.

Interesting,  Can you supply exact reproducabilty instructions (including exact versions of the Trilinos and ForTrilinos repos)?

**Comment by aprokop** [comment] 2017-12-19 20:37
@bartlettroscoe You are welcome to use the ForTrilinos container (the instructions are [here](https://fortrilinos.readthedocs.io/en/latest/developer_tools.html)). Fire it up and point it to the ForTrilinos prior to the fix, and run the `docker_cmake` from `scripts`.

I'm closing this issue as the fix has now been pushed to `master`. Please reopen it if this does not fix the failures.

**Closed** 2017-12-19 20:38 UTC

**Comment by bartlettroscoe** [comment] 2017-12-19 20:40
@aprokop,

> I'm closing this issue as the fix has now been pushed to master. Please reopen it if this does not fix the failures.

I need to warn you that if you clone the most recent version of Trilinos 'develop' that I just pushed, you will not longer be able to configure ForTrilinos inside of Trilinos as an inserted package.  Do you want me to issue a PR to allow ForTrilinos to be built as an extra package in an extra repo?

**Comment by aprokop** [comment] 2017-12-19 20:42
> I need to warn you that if you clone the most recent version of Trilinos 'develop' that I just pushed, you will not longer be able to configure ForTrilinos inside of Trilinos as an inserted package.

Is there a reason to do this now that the issue is fixed? I'm not sure about ramifications of being an external package. ForTrilinos should be released together with Trilinos when it releases (12.12, 12.14, etc). Would being external prohibit that? @jwillenbring

**Comment by bartlettroscoe** [comment] 2017-12-19 20:45
Is ForTrilinos getting related in official Trilinos releases?  There is no automated testing for ForTrilinos at all is there?

**Comment by aprokop** [comment] 2017-12-19 20:47
When you say automated testing, are you talking within ForTrilinos (there is) or integration with Trilinos? I assume that when it's the release time, the framework team will test Trilinos and ForTrilinos together to push the release. However, in between releases, the `master` of Trilinos and `master` of ForTrilinos are allowed to not work together.

**Comment by bartlettroscoe** [comment] 2017-12-19 20:51
There is zero testing of ForTrilinos showing up on the Trilinos CDash site, for example:

* https://testing.sandia.gov/cdash/viewSubProjects.php?project=Trilinos&date=2017-12-18

and there is no record of ForTrilinos being tested in all recorded history:

* https://testing.sandia.gov/cdash/index.php?subproject=ForTrilinos&project=Trilinos&date=2017-12-18&filtercount=1&showfilters=1&field1=buildstarttime&compare1=84&value1=now

Trilinos should not be release packages that have zero automated testing, should it?

I think we need to discuss the relationship between ForTrilinos and Trilinos and especially the Trilinos and ForTrilinos branches.  The breakage in trilinos/Trilinos#2085 demonstrates that.

**Comment by aprokop** [comment] 2017-12-19 20:55
@bartlettroscoe Yes, I think the discussion is in order. Unfortunately, we are currently waiting for @bmpersc to come back so it's not going to happen until after new year. 

I'm not the person to talk about why there has been no testing on the Dashboard with ForTrilinos. I can only attest to the current state. Right now, ForTrilinos sucessfully builds and tests with Trilinos 12.12 release (with a caveat of additional patches submitted in trilinos/Trilinos#2079. The plan is to push the current version to trilinos 12.12 branch, and then update it to be used with the latest Trilinos.

**Comment by bartlettroscoe** [comment] 2017-12-19 20:57
@aprokop,

What cmake configure options to you use to configure Triinos 12.12 with ForTrilinos?

Are you not testing ForTrilinos 'master' against Trilinos 'develop' or even 'master'?

**Comment by aprokop** [comment] 2017-12-19 21:00
> What cmake configure options to you use to configure Triinos 12.12 with ForTrilinos?

The options are in `scripts/docker_cmake` but I am posting them here for completion:
```bash
#!/bin/bash                                                                                                                                                   
EXTRA_ARGS=$@                                                                                                                                                 
                                                                                                                                                              
rm -f  CMakeCache.txt                                                                                                                                         
rm -rf CMakeFiles/                                                                                                                                            
                                                                                                                                                              
ARGS=(                                                                                                                                                        
    -D CMAKE_BUILD_TYPE=Debug                                                                                                                                 
                                                                                                                                                              
    -D BUILD_SHARED_LIBS=ON                                                                                                                                   
                                                                                                                                                              
    ### COMPILERS AND FLAGS ###                                                                                                                               
    -D Trilinos_ENABLE_Fortran=ON                                                                                                                             
    -D Trilinos_TPL_SYSTEM_INCLUDE_DIRS=ON                                                                                                                    
    -D CMAKE_CXX_FLAGS="-Wall -Wpedantic"                                                                                                                     
    -D CMAKE_Fortran_FLAGS="-std=f2003"                                                                                                                       
                                                                                                                                                              
    ### TPLs ###                                                                                                                                              
    -D TPL_ENABLE_MPI=ON                                                                                                                                      
    -D TPL_ENABLE_BLAS=ON                                                                                                                                     
    -D TPL_ENABLE_LAPACK=ON                                                                                                                                   
                                                                                                                                                              
    ### ETI ###                                                                                                                                               
    -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION=ON                                                                                                              
        -D Tpetra_INST_INT_INT=OFF                                                                                                                            
        -D Tpetra_INST_INT_LONG=OFF                                                                                                                           
        -D Tpetra_INST_INT_LONG_LONG=ON                                                                                                                       
                                                                                                                                                              
    ### PACKAGES CONFIGURATION ###                                                                                                                            
    -D Trilinos_ENABLE_ALL_PACKAGES=OFF 
    -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF                                                                                                              
                                                                                                                                                              
    -D Trilinos_ENABLE_TESTS=OFF                                                                                                                              
    -D Trilinos_ENABLE_EXAMPLES=OFF                                                                                                                           
                                                                                                                                                              
    -D Trilinos_ENABLE_Amesos2=ON                                                                                                                             
    -D Trilinos_ENABLE_Anasazi=ON                                                                                                                             
    -D Trilinos_ENABLE_Belos=ON                                                                                                                               
    -D Trilinos_ENABLE_Epetra=OFF                                                                                                                             
    -D Trilinos_ENABLE_Ifpack2=ON                                                                                                                             
    -D Trilinos_ENABLE_MueLu=ON                                                                                                                               
    -D Trilinos_ENABLE_Stratimikos=ON                                                                                                                         
    -D Trilinos_ENABLE_Tpetra=ON                                                                                                                              
    -D Trilinos_ENABLE_Thyra=ON                                                                                                                               
                                                                                                                                                              
    ### FORTRILINOS ###                                                                                                                                       
    -D Trilinos_ENABLE_ForTrilinos=ON                                                                                                                         
        -D ForTrilinos_ENABLE_EXAMPLES=ON                                                                                                                     
        -D ForTrilinos_ENABLE_TESTS=ON                                                                                                                        
    )                                                                                                                                                         
cmake "${ARGS[@]}" $EXTRA_ARGS $TRILINOS_DIR
```

> Are you not testing ForTrilinos 'master' against Trilinos 'develop' or even 'master'?

No, currently we are only testing against Trilinos 12.12. The reason for that is that the automatically generated interfaces work only for that version. As the interfaces in Tpetra change with time, this requires updating ForTrilinos interfaces.

**Comment by jwillenbring** [comment] 2017-12-19 21:33
Until @aprokop recently updated ForTrilinos, the package was essentially an obsolete version. I agree we should have a discussion after the new year about how to test ForTrilinos, what the expectations will be as far as breakages and releases. Thanks for fixing this issue.
